home:
    path: /
    controller: App\Controller\DefaultController::index

projects:
    path: /{_locale}/projects
    controller: App\Controller\DefaultController::projects

cv:
    path: /{_locale}/cv
    controller: App\Controller\DefaultController::cv
