index:
    path: /
    controller: App\Controller\DefaultController::index

cv:
    path: /cv
    controller: App\Controller\DefaultController::cv

projects:
    path: /projects
    controller: App\Controller\DefaultController::projects

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact